version: v1.3.0

dsn: postgres://postgres:postgres@postgres:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:5173
        - http://localhost:6868
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:5173/
  allowed_return_urls:
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:6868

  methods:
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: EMS
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: microsoft
            provider: microsoft
            client_id: placeholder
            client_secret: placeholder
            microsoft_tenant: common
            mapper_url: file:///etc/config/kratos/microsoft-claims-mapper.jsonnet
            scope:
              - openid
              - email
              - profile

  flows:
    error:
      ui_url: http://localhost:5173/auth/error

    settings:
      ui_url: http://localhost:5173/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://localhost:5173/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://localhost:5173/auth/verification
      use: code
      after:
        default_browser_return_url: http://localhost:5173/

    logout:
      after:
        default_browser_return_url: http://localhost:5173/auth/login

    login:
      ui_url: http://localhost:5173/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:5173/auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

# Secrets are provided via SECRETS_COOKIE and SECRETS_CIPHER env vars

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: argon2
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

session:
  lifespan: 24h
  cookie:
    domain: localhost
    same_site: Lax
