// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceStatus string

const (
	AttendanceStatusAttended  AttendanceStatus = "attended"
	AttendanceStatusNoShow    AttendanceStatus = "no_show"
	AttendanceStatusCheckedIn AttendanceStatus = "checked_in"
)

func (e *AttendanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceStatus(s)
	case string:
		*e = AttendanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceStatus: %T", src)
	}
	return nil
}

type NullAttendanceStatus struct {
	AttendanceStatus AttendanceStatus `json:"attendance_status"`
	Valid            bool             `json:"valid"` // Valid is true if AttendanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceStatus), nil
}

type Format string

const (
	FormatOnline  Format = "online"
	FormatOffline Format = "offline"
)

func (e *Format) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Format(s)
	case string:
		*e = Format(s)
	default:
		return fmt.Errorf("unsupported scan type for Format: %T", src)
	}
	return nil
}

type NullFormat struct {
	Format Format `json:"format"`
	Valid  bool   `json:"valid"` // Valid is true if Format is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormat) Scan(value interface{}) error {
	if value == nil {
		ns.Format, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Format.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Format), nil
}

type OrganizationStatus string

const (
	OrganizationStatusActive   OrganizationStatus = "active"
	OrganizationStatusArchived OrganizationStatus = "archived"
	OrganizationStatusFrozen   OrganizationStatus = "frozen"
)

func (e *OrganizationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationStatus(s)
	case string:
		*e = OrganizationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationStatus: %T", src)
	}
	return nil
}

type NullOrganizationStatus struct {
	OrganizationStatus OrganizationStatus `json:"organization_status"`
	Valid              bool               `json:"valid"` // Valid is true if OrganizationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationStatus), nil
}

type RegistrationStatus string

const (
	RegistrationStatusRegistered RegistrationStatus = "registered"
	RegistrationStatusCancelled  RegistrationStatus = "cancelled"
	RegistrationStatusWaitlist   RegistrationStatus = "waitlist"
)

func (e *RegistrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegistrationStatus(s)
	case string:
		*e = RegistrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RegistrationStatus: %T", src)
	}
	return nil
}

type NullRegistrationStatus struct {
	RegistrationStatus RegistrationStatus `json:"registration_status"`
	Valid              bool               `json:"valid"` // Valid is true if RegistrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegistrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RegistrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegistrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegistrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegistrationStatus), nil
}

type Event struct {
	ID             int32              `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	UserID         int32              `json:"user_id"`
	OrganizationID int32              `json:"organization_id"`
	Location       string             `json:"location"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Format         NullFormat         `json:"format"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EventAttendance struct {
	ID             int32              `json:"id"`
	RegistrationID int32              `json:"registration_id"`
	Status         AttendanceStatus   `json:"status"`
	CheckedInAt    pgtype.Timestamptz `json:"checked_in_at"`
	CheckedInBy    pgtype.Int4        `json:"checked_in_by"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EventRegistration struct {
	ID           int32              `json:"id"`
	EventID      int32              `json:"event_id"`
	UserID       int32              `json:"user_id"`
	Status       RegistrationStatus `json:"status"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EventTag struct {
	EventID int32 `json:"event_id"`
	TagID   int32 `json:"tag_id"`
}

type Organization struct {
	ID                 int32                  `json:"id"`
	Title              string                 `json:"title"`
	ImageUrl           pgtype.Text            `json:"image_url"`
	Description        pgtype.Text            `json:"description"`
	OrganizationTypeID int32                  `json:"organization_type_id"`
	Instagram          pgtype.Text            `json:"instagram"`
	TelegramChannel    pgtype.Text            `json:"telegram_channel"`
	TelegramChat       pgtype.Text            `json:"telegram_chat"`
	Website            pgtype.Text            `json:"website"`
	Youtube            pgtype.Text            `json:"youtube"`
	Tiktok             pgtype.Text            `json:"tiktok"`
	Linkedin           pgtype.Text            `json:"linkedin"`
	Status             NullOrganizationStatus `json:"status"`
	CreatedAt          pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz     `json:"updated_at"`
}

type OrganizationType struct {
	ID        int32              `json:"id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int32              `json:"id"`
	KratosID  pgtype.Text        `json:"kratos_id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	ID             int32 `json:"id"`
	UserID         int32 `json:"user_id"`
	OrganizationID int32 `json:"organization_id"`
	RoleID         int32 `json:"role_id"`
}
