// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationTypes = `-- name: CountOrganizationTypes :one
SELECT COUNT(*) FROM organization_types
`

func (q *Queries) CountOrganizationTypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationTypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (title, image_url, description, organization_type_id, instagram, telegram_channel, telegram_chat, website, youtube, tiktok, linkedin, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, COALESCE($12, 'active'))
RETURNING id, title, image_url, description, organization_type_id, instagram, telegram_channel, telegram_chat, website, youtube, tiktok, linkedin, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Title              string      `json:"title"`
	ImageUrl           pgtype.Text `json:"image_url"`
	Description        pgtype.Text `json:"description"`
	OrganizationTypeID int32       `json:"organization_type_id"`
	Instagram          pgtype.Text `json:"instagram"`
	TelegramChannel    pgtype.Text `json:"telegram_channel"`
	TelegramChat       pgtype.Text `json:"telegram_chat"`
	Website            pgtype.Text `json:"website"`
	Youtube            pgtype.Text `json:"youtube"`
	Tiktok             pgtype.Text `json:"tiktok"`
	Linkedin           pgtype.Text `json:"linkedin"`
	Status             interface{} `json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Title,
		arg.ImageUrl,
		arg.Description,
		arg.OrganizationTypeID,
		arg.Instagram,
		arg.TelegramChannel,
		arg.TelegramChat,
		arg.Website,
		arg.Youtube,
		arg.Tiktok,
		arg.Linkedin,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.Description,
		&i.OrganizationTypeID,
		&i.Instagram,
		&i.TelegramChannel,
		&i.TelegramChat,
		&i.Website,
		&i.Youtube,
		&i.Tiktok,
		&i.Linkedin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationType = `-- name: CreateOrganizationType :one
INSERT INTO organization_types (title)
VALUES ($1)
RETURNING id, title, created_at, updated_at
`

func (q *Queries) CreateOrganizationType(ctx context.Context, title string) (OrganizationType, error) {
	row := q.db.QueryRow(ctx, createOrganizationType, title)
	var i OrganizationType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const deleteOrganizationType = `-- name: DeleteOrganizationType :exec
DELETE FROM organization_types WHERE id = $1
`

func (q *Queries) DeleteOrganizationType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrganizationType, id)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, title, image_url, description, organization_type_id, instagram, telegram_channel, telegram_chat, website, youtube, tiktok, linkedin, status, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int32) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.Description,
		&i.OrganizationTypeID,
		&i.Instagram,
		&i.TelegramChannel,
		&i.TelegramChat,
		&i.Website,
		&i.Youtube,
		&i.Tiktok,
		&i.Linkedin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationType = `-- name: GetOrganizationType :one
SELECT id, title, created_at, updated_at FROM organization_types WHERE id = $1
`

func (q *Queries) GetOrganizationType(ctx context.Context, id int32) (OrganizationType, error) {
	row := q.db.QueryRow(ctx, getOrganizationType, id)
	var i OrganizationType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationsByUserRoles = `-- name: GetOrganizationsByUserRoles :many
SELECT DISTINCT o.id, o.title, o.image_url, o.description, o.organization_type_id, o.instagram, o.telegram_channel, o.telegram_chat, o.website, o.youtube, o.tiktok, o.linkedin, o.status, o.created_at, o.updated_at
FROM organizations o
INNER JOIN user_roles ur ON ur.organization_id = o.id
INNER JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1 AND r.name = ANY($2::text[])
`

type GetOrganizationsByUserRolesParams struct {
	UserID int32    `json:"user_id"`
	Roles  []string `json:"roles"`
}

func (q *Queries) GetOrganizationsByUserRoles(ctx context.Context, arg GetOrganizationsByUserRolesParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsByUserRoles, arg.UserID, arg.Roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.Description,
			&i.OrganizationTypeID,
			&i.Instagram,
			&i.TelegramChannel,
			&i.TelegramChat,
			&i.Website,
			&i.Youtube,
			&i.Tiktok,
			&i.Linkedin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationTypes = `-- name: ListOrganizationTypes :many
SELECT id, title, created_at, updated_at FROM organization_types
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListOrganizationTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizationTypes(ctx context.Context, arg ListOrganizationTypesParams) ([]OrganizationType, error) {
	rows, err := q.db.Query(ctx, listOrganizationTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationType
	for rows.Next() {
		var i OrganizationType
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, title, image_url, description, organization_type_id, instagram, telegram_channel, telegram_chat, website, youtube, tiktok, linkedin, status, created_at, updated_at FROM organizations
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.Description,
			&i.OrganizationTypeID,
			&i.Instagram,
			&i.TelegramChannel,
			&i.TelegramChat,
			&i.Website,
			&i.Youtube,
			&i.Tiktok,
			&i.Linkedin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET title = COALESCE($1, title),
    image_url = COALESCE($2, image_url),
    description = COALESCE($3, description),
    organization_type_id = COALESCE($4, organization_type_id),
    instagram = COALESCE($5, instagram),
    telegram_channel = COALESCE($6, telegram_channel),
    telegram_chat = COALESCE($7, telegram_chat),
    website = COALESCE($8, website),
    youtube = COALESCE($9, youtube),
    tiktok = COALESCE($10, tiktok),
    linkedin = COALESCE($11, linkedin),
    status = COALESCE($12, status),
    updated_at = NOW()
WHERE id = $13
RETURNING id, title, image_url, description, organization_type_id, instagram, telegram_channel, telegram_chat, website, youtube, tiktok, linkedin, status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	Title              pgtype.Text            `json:"title"`
	ImageUrl           pgtype.Text            `json:"image_url"`
	Description        pgtype.Text            `json:"description"`
	OrganizationTypeID pgtype.Int4            `json:"organization_type_id"`
	Instagram          pgtype.Text            `json:"instagram"`
	TelegramChannel    pgtype.Text            `json:"telegram_channel"`
	TelegramChat       pgtype.Text            `json:"telegram_chat"`
	Website            pgtype.Text            `json:"website"`
	Youtube            pgtype.Text            `json:"youtube"`
	Tiktok             pgtype.Text            `json:"tiktok"`
	Linkedin           pgtype.Text            `json:"linkedin"`
	Status             NullOrganizationStatus `json:"status"`
	ID                 int32                  `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Title,
		arg.ImageUrl,
		arg.Description,
		arg.OrganizationTypeID,
		arg.Instagram,
		arg.TelegramChannel,
		arg.TelegramChat,
		arg.Website,
		arg.Youtube,
		arg.Tiktok,
		arg.Linkedin,
		arg.Status,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ImageUrl,
		&i.Description,
		&i.OrganizationTypeID,
		&i.Instagram,
		&i.TelegramChannel,
		&i.TelegramChat,
		&i.Website,
		&i.Youtube,
		&i.Tiktok,
		&i.Linkedin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationType = `-- name: UpdateOrganizationType :one
UPDATE organization_types
SET title = COALESCE($1, title),
    updated_at = NOW()
WHERE id = $2
RETURNING id, title, created_at, updated_at
`

type UpdateOrganizationTypeParams struct {
	Title pgtype.Text `json:"title"`
	ID    int32       `json:"id"`
}

func (q *Queries) UpdateOrganizationType(ctx context.Context, arg UpdateOrganizationTypeParams) (OrganizationType, error) {
	row := q.db.QueryRow(ctx, updateOrganizationType, arg.Title, arg.ID)
	var i OrganizationType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
