// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddEventTag(ctx context.Context, arg AddEventTagParams) error
	CancelEventRegistration(ctx context.Context, id int32) error
	CountEventAttendanceStats(ctx context.Context, eventID int32) (CountEventAttendanceStatsRow, error)
	CountEventRegistrations(ctx context.Context, eventID int32) (int64, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	CountOrganizationTypes(ctx context.Context) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountTags(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventAttendance(ctx context.Context, arg CreateEventAttendanceParams) (EventAttendance, error)
	CreateEventRegistration(ctx context.Context, arg CreateEventRegistrationParams) (EventRegistration, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationType(ctx context.Context, title string) (OrganizationType, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserFromKratos(ctx context.Context, arg CreateUserFromKratosParams) (User, error)
	DeleteEvent(ctx context.Context, id int32) error
	DeleteOrganization(ctx context.Context, id int32) error
	DeleteOrganizationType(ctx context.Context, id int32) error
	DeleteTag(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetEventAttendanceByRegistration(ctx context.Context, registrationID int32) (EventAttendance, error)
	GetEventAttendanceForEvent(ctx context.Context, eventID int32) ([]EventAttendance, error)
	GetEventRegistration(ctx context.Context, id int32) (EventRegistration, error)
	GetEventRegistrationByEventAndUser(ctx context.Context, arg GetEventRegistrationByEventAndUserParams) (EventRegistration, error)
	GetEventRegistrations(ctx context.Context, arg GetEventRegistrationsParams) ([]EventRegistration, error)
	GetEventTagIDs(ctx context.Context, eventID int32) ([]int32, error)
	GetEventTags(ctx context.Context, eventID int32) ([]Tag, error)
	GetEventsByTagID(ctx context.Context, tagID int32) ([]Event, error)
	GetOrganization(ctx context.Context, id int32) (Organization, error)
	GetOrganizationType(ctx context.Context, id int32) (OrganizationType, error)
	GetOrganizationsByUserRoles(ctx context.Context, arg GetOrganizationsByUserRolesParams) ([]Organization, error)
	GetTag(ctx context.Context, id int32) (Tag, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByKratosID(ctx context.Context, kratosID pgtype.Text) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRegistrations(ctx context.Context, userID int32) ([]EventRegistration, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListOrganizationTypes(ctx context.Context, arg ListOrganizationTypesParams) ([]OrganizationType, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveEventTags(ctx context.Context, eventID int32) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateEventAttendance(ctx context.Context, arg UpdateEventAttendanceParams) (EventAttendance, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationType(ctx context.Context, arg UpdateOrganizationTypeParams) (OrganizationType, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
