// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEventRegistration = `-- name: CancelEventRegistration :exec
UPDATE event_registrations
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelEventRegistration(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelEventRegistration, id)
	return err
}

const countEventAttendanceStats = `-- name: CountEventAttendanceStats :one
SELECT 
    COUNT(*) FILTER (WHERE er.status = 'registered') as total_registered,
    COUNT(*) FILTER (WHERE ea.status = 'attended') as total_attended,
    COUNT(*) FILTER (WHERE ea.status = 'no_show') as total_no_show
FROM event_registrations er
LEFT JOIN event_attendance ea ON ea.registration_id = er.id
WHERE er.event_id = $1
`

type CountEventAttendanceStatsRow struct {
	TotalRegistered int64 `json:"total_registered"`
	TotalAttended   int64 `json:"total_attended"`
	TotalNoShow     int64 `json:"total_no_show"`
}

func (q *Queries) CountEventAttendanceStats(ctx context.Context, eventID int32) (CountEventAttendanceStatsRow, error) {
	row := q.db.QueryRow(ctx, countEventAttendanceStats, eventID)
	var i CountEventAttendanceStatsRow
	err := row.Scan(&i.TotalRegistered, &i.TotalAttended, &i.TotalNoShow)
	return i, err
}

const countEventRegistrations = `-- name: CountEventRegistrations :one
SELECT COUNT(*) FROM event_registrations WHERE event_id = $1
`

func (q *Queries) CountEventRegistrations(ctx context.Context, eventID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countEventRegistrations, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEventAttendance = `-- name: CreateEventAttendance :one
INSERT INTO event_attendance (registration_id, status, checked_in_at, checked_in_by, notes)
VALUES ($1, $2, CASE WHEN $5::boolean THEN NOW() ELSE NULL END, $3, $4)
RETURNING id, registration_id, status, checked_in_at, checked_in_by, notes, created_at, updated_at
`

type CreateEventAttendanceParams struct {
	RegistrationID int32            `json:"registration_id"`
	Status         AttendanceStatus `json:"status"`
	CheckedInBy    pgtype.Int4      `json:"checked_in_by"`
	Notes          pgtype.Text      `json:"notes"`
	MarkCheckedIn  bool             `json:"mark_checked_in"`
}

func (q *Queries) CreateEventAttendance(ctx context.Context, arg CreateEventAttendanceParams) (EventAttendance, error) {
	row := q.db.QueryRow(ctx, createEventAttendance,
		arg.RegistrationID,
		arg.Status,
		arg.CheckedInBy,
		arg.Notes,
		arg.MarkCheckedIn,
	)
	var i EventAttendance
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventRegistration = `-- name: CreateEventRegistration :one
INSERT INTO event_registrations (event_id, user_id, status, registered_at)
VALUES ($1, $2, 'registered', NOW())
RETURNING id, event_id, user_id, status, registered_at, cancelled_at, created_at, updated_at
`

type CreateEventRegistrationParams struct {
	EventID int32 `json:"event_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) CreateEventRegistration(ctx context.Context, arg CreateEventRegistrationParams) (EventRegistration, error) {
	row := q.db.QueryRow(ctx, createEventRegistration, arg.EventID, arg.UserID)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.RegisteredAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAttendanceByRegistration = `-- name: GetEventAttendanceByRegistration :one
SELECT id, registration_id, status, checked_in_at, checked_in_by, notes, created_at, updated_at FROM event_attendance WHERE registration_id = $1
`

func (q *Queries) GetEventAttendanceByRegistration(ctx context.Context, registrationID int32) (EventAttendance, error) {
	row := q.db.QueryRow(ctx, getEventAttendanceByRegistration, registrationID)
	var i EventAttendance
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAttendanceForEvent = `-- name: GetEventAttendanceForEvent :many
SELECT ea.id, ea.registration_id, ea.status, ea.checked_in_at, ea.checked_in_by, ea.notes, ea.created_at, ea.updated_at
FROM event_attendance ea
INNER JOIN event_registrations er ON er.id = ea.registration_id
WHERE er.event_id = $1
`

func (q *Queries) GetEventAttendanceForEvent(ctx context.Context, eventID int32) ([]EventAttendance, error) {
	rows, err := q.db.Query(ctx, getEventAttendanceForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventAttendance
	for rows.Next() {
		var i EventAttendance
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Status,
			&i.CheckedInAt,
			&i.CheckedInBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventRegistration = `-- name: GetEventRegistration :one
SELECT id, event_id, user_id, status, registered_at, cancelled_at, created_at, updated_at FROM event_registrations WHERE id = $1
`

func (q *Queries) GetEventRegistration(ctx context.Context, id int32) (EventRegistration, error) {
	row := q.db.QueryRow(ctx, getEventRegistration, id)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.RegisteredAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventRegistrationByEventAndUser = `-- name: GetEventRegistrationByEventAndUser :one
SELECT id, event_id, user_id, status, registered_at, cancelled_at, created_at, updated_at FROM event_registrations WHERE event_id = $1 AND user_id = $2
`

type GetEventRegistrationByEventAndUserParams struct {
	EventID int32 `json:"event_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) GetEventRegistrationByEventAndUser(ctx context.Context, arg GetEventRegistrationByEventAndUserParams) (EventRegistration, error) {
	row := q.db.QueryRow(ctx, getEventRegistrationByEventAndUser, arg.EventID, arg.UserID)
	var i EventRegistration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.RegisteredAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventRegistrations = `-- name: GetEventRegistrations :many
SELECT id, event_id, user_id, status, registered_at, cancelled_at, created_at, updated_at FROM event_registrations
WHERE event_id = $1
ORDER BY registered_at DESC
LIMIT $2 OFFSET $3
`

type GetEventRegistrationsParams struct {
	EventID int32 `json:"event_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetEventRegistrations(ctx context.Context, arg GetEventRegistrationsParams) ([]EventRegistration, error) {
	rows, err := q.db.Query(ctx, getEventRegistrations, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRegistration
	for rows.Next() {
		var i EventRegistration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.RegisteredAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRegistrations = `-- name: GetUserRegistrations :many
SELECT id, event_id, user_id, status, registered_at, cancelled_at, created_at, updated_at FROM event_registrations
WHERE user_id = $1
ORDER BY registered_at DESC
`

func (q *Queries) GetUserRegistrations(ctx context.Context, userID int32) ([]EventRegistration, error) {
	rows, err := q.db.Query(ctx, getUserRegistrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRegistration
	for rows.Next() {
		var i EventRegistration
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.RegisteredAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventAttendance = `-- name: UpdateEventAttendance :one
UPDATE event_attendance
SET status = $2, notes = COALESCE($3, notes), updated_at = NOW()
WHERE registration_id = $1
RETURNING id, registration_id, status, checked_in_at, checked_in_by, notes, created_at, updated_at
`

type UpdateEventAttendanceParams struct {
	RegistrationID int32            `json:"registration_id"`
	Status         AttendanceStatus `json:"status"`
	Notes          pgtype.Text      `json:"notes"`
}

func (q *Queries) UpdateEventAttendance(ctx context.Context, arg UpdateEventAttendanceParams) (EventAttendance, error) {
	row := q.db.QueryRow(ctx, updateEventAttendance, arg.RegistrationID, arg.Status, arg.Notes)
	var i EventAttendance
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Status,
		&i.CheckedInAt,
		&i.CheckedInBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
